# Generated by Django 3.2.3 on 2021-05-22 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_rename_messege_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
